### ISSUE TITLE
There is no release available

### ISSUE THREAD

**Issue by fcyu** [yeastrc/limelight-import-msfragger-tsv#1]

**Comment by mriffle** [comment]
Thanks for alerting me to this, I've just created a release.

Mike

**Comment by fcyu** [comment]
Thanks for your prompt reply.

I will try it and let you know if I have any question.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Mike,

It works! 

May I ask a question? Does `msFragger2LimelightXML` estimate FDR using the expectation from the tsv file? 

May I also give one suggestion? `msFragger2LimelightXML.jar`'s options are 
```
[-hvV] [--open-mod] -f=<fastaFile> -m=<tsvFile> -o=<outFile> -p=<msFraggerConfFile>
```
,while `msFraggerTPP2LimelightXML.jar` switches `-m` and `-p` according to the README: 
```
[-hvV] [--open-mod] -f=<fastaFile> -m=<msFraggerConfFile> -o=<outFile> -p=<pepXMLFile>
```

I am not sure if it is on purpose. Could unify them if it is OK.

Best,

Fengchao

**Comment by mriffle** [comment]
Hi Fengchao,

Yes, FDR estimations are done with the E-values.

Thank you for your suggestion about the CLI params. Yeah, that is definitely confusing. I'll take a closer look at that today and respond here w/ any changes.

Mike

**Comment by mriffle** [comment]
Oh, I should point out that you don't have to use the estimated FDRs as your filter in Limelight. You can override that in the web interface if you would prefer to use E-values as they come out of Fragger.

**Comment by mriffle** [comment]
I have updated the MSFragger TPP (pepXML) converter to use command line arguments more consistent with this one. Namely -p now points to the params file. And now -x will point to the pepXML file.

**Comment by fcyu** [comment]
Sounds great! And, yes, I figured out how to override the FDR threshold. 

I think it is good to closed this issue now.

Best,

Fengchao
