### ISSUE TITLE
The name msFragger2LimelightXML in the README seems incorrect

### ISSUE THREAD

**Issue by fcyu** [yeastrc/limelight-import-msfragger-tsv#2]

**Comment by mriffle** [comment]
Thanks @fcyu,

I do have it currently set up to be "msFragger2LimelightXML.jar"  I'll create the release shortly, thanks for your other issue report.

Do you think it should have a different name? I'm open to suggestions.

Mike

**Comment by fcyu** [comment]
Hi Mike,

Then, that is fine. 

Best,

Fengchao
